### PR TITLE
User-Service: Project setup, docker, db, etc.

### LINKED ISSUE #1: User Service: Project Setup
- python project setup 
- remake api endpoints to fit database
- make database interface
- switch to aau server
- docker

### LINKED ISSUE #2: User Service; Test

### PR DESCRIPTION
**Pull request by MJHC**
This pull request have setup the repo as a python project, with a fast api server and endpoints for user actions and validation. 

this also includes a dockerfile and database interface.

resolves #1 
resolves #2

### CODE REVIEW

**Comment by Schwartz123** [comment]
problem when adding a new user where gender can be set to other things than male and female

**Review by Schwartz123 — CHANGES_REQUESTED** [review]
Gender can be other thing than male and female

**Review by APaludan — APPROVED** [review]
👍👍👍

**Review by Schwartz123 — APPROVED** [review]
Lookin good

**Pull request merged**
